project:
  type: website

website:
  title: "Using xgboost with stops data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: testingstops.qmd
        text: Testing Stops
      - href: traffic-stops-xgboost.qmd
        text: Traffic Stops with XGBoost

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



